import { defineConfig } from 'tsup';
import fs from 'fs';
import path from 'path';

const outDir = '../luci-app-prokop/htdocs/luci-static/resources/view/prokop';

// Each entry is a LuCI module of its own: view.prokop.<name>. main.js is
// loaded by every Prokop page; the others only by the page that shows them
// (2026-10-05 audit). They are built without code splitting: LuCI modules
// cannot import chunks, so a module other than main gets its own copy of
// what it imports and must import nothing with state of main.js
// (src/modules/tests/bundles.test.js).
export const entries = {
  main: 'src/main.ts',
  component_progress: 'src/modules/componentProgress.ts',
  devices_view: 'src/modules/devicesView.ts',
};

// The bundle's `export {...}` becomes LuCI's `return baseclass.extend({...})`.
function patchLuciModule(file: string) {
  let code = fs.readFileSync(file, 'utf8');

  code = code.replace(/export\s*{([\s\S]*?)}/, (match, group) => {
    // A minified build exports `local as name`.
    const members = group
      .split(',')
      .map((item) => item.trim())
      .filter(Boolean)
      .map((item) => {
        const [local, name] = item.split(/\s+as\s+/);
        return name && name !== local ? `${name}:${local}` : local;
      });
    return `return baseclass.extend({${members.join(',')}})`;
  });

  // LuCI's "require" directives, one per line as LuCI and the tests
  // read them; the minifier joins them.
  code = code.replace(/^((?:\/\/[^\n]*\n|"[^"\n]*";\s*)+)/, (prologue) =>
    prologue.replace(/";\s*"/g, '";\n"').replace(/";\s*$/, '";\n'),
  );

  fs.writeFileSync(file, code, 'utf8');
  console.log(`✅ Patched LuCI build: ${file}`);
}

export default defineConfig({
  // `tsup` builds every module; `tsup src/main.ts` only main.js.
  entry: entries,
  format: ['esm'], // пусть tsup генерит export {...}
  outDir,
  outExtension: () => ({ js: '.js' }),
  dts: false,
  clean: false,
  sourcemap: false,
  splitting: false,
  banner: {
    js: `// This file is autogenerated, please don't change manually \n"use strict";`,
  },
  // 2026-10-04 audit, optimization 25: uhttpd serves main.js uncompressed
  // and LuCI parses it on every Prokop page.
  minify: true,
  esbuildOptions(options) {
    options.legalComments = 'none';
  },
  onSuccess: async () => {
    for (const name of Object.keys(entries)) {
      const file = path.join(outDir, `${name}.js`);
      // `tsup src/main.ts` writes main.js only; the others were patched
      // before and end without an `export {...}`.
      if (
        fs.existsSync(file) &&
        /export\s*{[^}]*};?\s*$/.test(fs.readFileSync(file, 'utf8'))
      )
        patchLuciModule(file);
    }
  },
});
