import { defineConfig } from 'tsup';
import fs from 'fs';
import path from 'path';

export default defineConfig({
  entry: ['src/main.ts'],
  format: ['esm'], // пусть tsup генерит export {...}
  outDir: '../luci-app-prokop/htdocs/luci-static/resources/view/prokop',
  outExtension: () => ({ js: '.js' }),
  dts: false,
  clean: false,
  sourcemap: false,
  banner: {
    js: `// This file is autogenerated, please don't change manually \n"use strict";`,
  },
  // 2026-10-04 audit, optimization 25: uhttpd serves main.js uncompressed
  // and LuCI parses it on every Prokop page.
  minify: true,
  esbuildOptions(options) {
    options.legalComments = 'none';
  },
  onSuccess: () => {
    const outDir =
      '../luci-app-prokop/htdocs/luci-static/resources/view/prokop';
    const file = path.join(outDir, 'main.js');
    let code = fs.readFileSync(file, 'utf8');

    code = code.replace(/export\s*{([\s\S]*?)}/, (match, group) => {
      // A minified build exports `local as name`.
      const members = group
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean)
        .map((item) => {
          const [local, name] = item.split(/\s+as\s+/);
          return name && name !== local ? `${name}:${local}` : local;
        });
      return `return baseclass.extend({${members.join(',')}})`;
    });

    // LuCI's "require" directives, one per line as LuCI and the tests
    // read them; the minifier joins them.
    code = code.replace(/^((?:\/\/[^\n]*\n|"[^"\n]*";\s*)+)/, (prologue) =>
      prologue.replace(/";\s*"/g, '";\n"').replace(/";\s*$/, '";\n'),
    );

    fs.writeFileSync(file, code, 'utf8');
    console.log(`✅ Patched LuCI build: ${file}`);
  },
});
